### ISSUE TITLE
App crashes on android 4.4.2

### ISSUE THREAD

**Issue by maxkomarychev** [bugsnag/bugsnag-react-native#199]
```
01-10 16:13:35.022 2762-2762/my.app.package E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: my.app.package, PID: 2762
                                                                 java.lang.VerifyError: com/bugsnag/BugsnagReactNative
                                                                     at my.app.package.MainApplication.onCreate(MainApplication.java:82)
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                     at dalvik.system.NativeStart.main(Native Method)
```

### Steps to reproduce

1. run the app from android studio

### Expected behavior
No crash

### Observed behavior

crash

### Environment

- react-native version: 0.50.4
- bugsnag-react-native version: ^2.3.2
- react-native-code-push version (if any): ^5.0.0-beta
- cocoapods version (if any): 1.3.1
- iOS/Android version(s): 4.4.2
- simulator/emulator or physical device?: android nexus4 emulator
- debug mode or production?: debug

### Additional information

it works fine in android >= 5
it works fine in release build

**Comment by fractalwrench** [comment]
@maxkomarychev thanks for the report. Would you be able to share the dependencies you're using in your `build.gradle` file and `package.json`, along with your buildToolsVersion, compileSdkVersion, minSdkVersion, and targetSdkVersion?

**Comment by fractalwrench** [comment]
Closing due to inactivity. Feel free to comment if this is still affecting you, and we'll reopen the issue.

**Comment by mhusnain030** [comment]
@fractalwrench facing the same issue with bugsnag. Please reopen the issue.
