### ISSUE TITLE
"No native client found" when running Jest tests on RN 0.56+

### ISSUE THREAD

**Issue by rajivshah3** [bugsnag/bugsnag-react-native#277]
### Description
After upgrading to RN 0.56 or 0.57, I get the following message on tests for components that call `bugsnag.leaveBreadcrumb` (I use it to track navigation events):
```

● Test suite failed to run
--
  |  
  | Bugsnag: No native client found. Is BugsnagReactNative installed in your native code project?
  |  
  | 5 \| configuration.appVersion = packageJson.version;
  | 6 \|
  | >  7 \| const bugsnag = new Client(configuration);
  | \|               ^
  | 8 \|
  | 9 \| /**
  | 10 \|  * Leaves navigation breadcrumbs to help determine what screen an error occurred on
  |  
  | at new Client (node_modules/bugsnag-react-native/src/Bugsnag.js:35:23)
  | at Object.<anonymous> (src/libs/bugsnag.js:7:15)
  | at Object.<anonymous> (src/ui/views/wallet/AdvancedSettings.js:8:16)
  | at Object.<anonymous> (__tests__/ui/views/wallet/AdvancedSettings.spec.js:6:25)


```

### Environment

Library versions:

```shell
├─ bugsnag-react-native@2.9.4
└─ react-native@0.57.0
```

- cocoapods version (if any) (`pod -v`): N/A
- iOS/Android version(s): N/A
- simulator/emulator or physical device?: N/A
- debug mode or production?: N/A

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example Repo
I was able to reproduce this by cloning the PR for the upgrade of the example project to 0.56 (#258) and then applying various fixes from StackOverflow and GitHub issues to resolve some generic issues from Jest: https://github.com/rajivshah3/bugsnag-react-native/tree/rn056-broken-repro

**Comment by fractalwrench** [comment]
Thanks for getting in touch @rajivshah3. I believe if you're using Jest, it may be necessary to [mock Bugsnag](https://jestjs.io/docs/en/tutorial-react-native#mock-native-modules-using-jestmock) in your tests, as the library uses native modules. Does this resolve your issue?

**Comment by rajivshah3** [comment]
Hi @fractalwrench ,
We currently use RN 0.51 and have mocked Bugsnag in the tests of each component that calls `bugsnag.leaveBreadcrumb` using the following:

```js
jest.mock('bugsnag-react-native', () => ({
    Configuration: jest.fn(),
    Client: jest.fn(() => ({ leaveBreadcrumb: jest.fn() })),
}));
```

This currently works for RN 0.51, but it seems like it no longer works for 0.56 and 0.57.

**Comment by fractalwrench** [comment]
@rajivshah3 this sounds like it may be an issue with React Native/Jest if your code has not otherwise changed. It looks like Jest was upgraded to [v23.4.1](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md) and v23.2.0 in 0.56 (which mentions refactoring mocking of native methods).

Do you still encounter this behaviour if you downgrade the Jest library?
