### ISSUE TITLE
com.facebook.react.bridge.NoSuchKeyExceptionReadableNativeMap.java:122 backgroundColor

### ISSUE THREAD

**Issue by patrickalbani** [bugsnag/bugsnag-react-native#281]
I use Fabric in android production app, after install bugsnag 2.10.2 with react-native 0.57 and put in production, started to receive error:

```
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: backgroundColor
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:126)
       at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:180)
       at com.facebook.react.uimanager.ViewProps.isLayoutOnly(ViewProps.java:234)
       at com.facebook.react.uimanager.NativeViewHierarchyOptimizer.isLayoutOnlyAndCollapsable(NativeViewHierarchyOptimizer.java:445)
       at com.facebook.react.uimanager.NativeViewHierarchyOptimizer.handleCreateView(NativeViewHierarchyOptimizer.java:92)
       at com.facebook.react.uimanager.UIImplementation.handleCreateView(UIImplementation.java:306)
       at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:298)
       at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:377)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:818)
```

Someone can help me to understand this?

**Comment by abartolo** [comment]
@patrickalbani What was the solution to this? I am seeing this same but I don't use this library.

**Comment by abartolo** [comment]
@all if anyone has this issue make sure sure "backgroundColor" value is never null or undefined. Before my logic wasn't breaking but after upgrading React Native this error occurred.

**Comment by harzkr** [comment]
Hi @abartolo,
I'm facing the same error, as soon as my App starts, I'm seeing simply backgroundColor, written as an error, as per your suggestion, I checked but I do not have any null/undefined values for any backgroundColor, could you exactly specify which backgroundColor is this

Much Thanks!

**Comment by douglasjunior** [comment]
I'm also start receiving this errors after update to RN 0.59 for some devices, but I have no idea whats is wrong.
