### ISSUE TITLE
com.facebook.react.bridge.NoSuchKeyException: offset

### ISSUE THREAD

**Issue by ChenZhaobin** [bugsnag/bugsnag-react-native#347]
Works well with IOS ,when it comes to android ,I got exception "com.facebook.react.bridge.NoSuchKeyException: offset",but I got no idea how to trace this.
> "devDependencies": {
>     "babel-eslint": "7.2.3",
>     "eslint": "4.4.1",
>     "eslint-plugin-flowtype": "2.35.0",
>     "eslint-plugin-import": "2.7.0",
>     "eslint-plugin-jsx-a11y": "6.0.2",
>     "eslint-plugin-prettier": "2.1.2",
>     "eslint-plugin-react": "7.1.0",
>     "eslint-plugin-react-native": "3.0.1",
>     "flow-bin": "0.78.0",
>     "flow-typed": "2.5.1",
>     "husky": "0.14.3",
>     "jest": "24.1.0",
>     "metro-react-native-babel-preset": "0.52.0",
>     "prettier": "1.5.3",
>     "react-test-renderer": "16.6.3"
>   },
>   "scripts": {
>     "start": "react-native start",
>     "android": "react-native run-android",
>     "ios": "react-native run-ios"
>   },
>   "jest": {
>     "preset": "react-native",
>     "transformIgnorePatterns": [
>       "node_modules/(?!(react-native|lottie-react-native|expo|react-native-maps|react-native-svg|react-native-branch|native-base-shoutem-theme|react-native-easy-grid|react-native-drawer|react-native-vector-icons|react-native-keyboard-aware-scroll-view|react-native-swiper|react-navigation|native-base|@expo|react-native-scrollable-tab-view|react-native-simple-modal|react-native-iphone-x-helper)/)"
>     ]
>   },
>   "dependencies": {
>     "@babel/plugin-proposal-decorators": "^7.4.0",
>     "babel-plugin-transform-runtime": "^6.23.0",
>     "color": "1.0.3",
>     "lodash": "4.17.10",
>     "mobx": "^4.3.1",
>     "mobx-react": "^5.1.0",
>     "moment": "2.13.0",
>     "native-base": "2.12.1",
>     "react": "16.6.3",
>     "react-native": "^0.58.5",
>     "react-native-action-button": "^2.8.5",
>     "react-native-dialog": "^5.6.0",
>     "react-native-gesture-handler": "^1.0.15",
>     "react-native-htmlview": "^0.13.0",
>     "react-native-image-crop-picker": "^0.23.1",
>     "react-native-modal-datetime-picker": "^7.2.0",
>     "react-native-modal-filter-picker": "^1.3.4",
>     "react-native-px2dp": "^1.1.0",
>     "react-native-snap-carousel": "^3.7.5",
>     "react-native-step-indicator": "0.0.11",
>     "react-native-swiper": "^1.5.14",
>     "react-native-timeline-listview": "^0.2.3",
>     "react-native-ui-kitten": "^3.1.2",
>     "react-native-vector-icons": "^6.3.0",
>     "react-navigation": "3.3.0",
>     "scheduler": "^0.12.0",
>     "socket.io-client": "^2.2.0",
>     "styled-components": "^3.4.5",
>     "victory-native": "^32.0.2"
>   },
> 

ReactNative: Exception in native call
    com.facebook.react.bridge.NoSuchKeyException: offset
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:120)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
        at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:166)
        at com.facebook.react.animated.ValueAnimatedNode.<init>(ValueAnimatedNode.java:29)
        at com.facebook.react.animated.NativeAnimatedNodesManager.createAnimatedNode(NativeAnimatedNodesManager.java:89)
        at com.facebook.react.animated.NativeAnimatedModule$4.execute(NativeAnimatedModule.java:202)
        at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:150)
        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:583)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:110)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by kattrali** [comment]
Hi @ChenZhaobin - it doesn't look `bugsnag-react-native` is in either the dependencies or the stacktrace. Maybe this error is from another library?
